name: Tiket.com Playwright QA Automation

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  schedule:
    - cron: '0 18 * * *' # 01:00 WIB nightly regression

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production


jobs:

  smoke-tests:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests (Production)
        env:
          ENV: production
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npx playwright test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-smoke
          path: playwright-report/
          retention-days: 30



  nightly-regression:
    if: github.event_name == 'schedule'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Nightly Regression (Production)
        env:
          ENV: production
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npx playwright test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-nightly
          path: playwright-report/
          retention-days: 30



  manual-tests:
    if: github.event_name == 'workflow_dispatch'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Manual Test (${{ github.event.inputs.environment }})
        env:
          ENV: ${{ github.event.inputs.environment }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npx playwright test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-manual
          path: playwright-report/
          retention-days: 30
